import type {Metadata} from 'next';
import './globals.css';
import localFont from 'next/font/local';
import {PropsWithChildren} from 'react';
import {environment} from '../environment/environment';

const segment = localFont({
    src: './Segment7-4Gml.otf',
    variable: '--font-segment'
});

export const metadata: Metadata = {
    title: `${environment.brandName}`,
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<PropsWithChildren>) {
    return (
        <html lang="en">
        <body className={segment.className}>{children}</body>
        </html>
    );
}
