import type {Metadata} from 'next';
import './globals.css';
import {PropsWithChildren} from 'react';
import {environment} from '../environment/environment';

export const metadata: Metadata = {
    title: `${environment.brandName}`,
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<PropsWithChildren>) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}
