name: "📥 Install"
description: "📥 Install dependencies"

runs:
  using: "composite"
  steps:
    - name: "📦 Cache node_modules"
      id: node-modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ runner.arch }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: "📥 Install dependencies"
      if: steps.node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
