name: "游댢 Deploy to GitHub"

on:
  # When you push changes: only affected projects will be build/deploy
  push:
    branches:
      - main
      - v2.0.x
  # When you manually trigger: all projects will be build/deploy
  workflow_dispatch:

concurrency: "deploy"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: "游닌 Checkout code"
        uses: actions/checkout@v4

      - name: "游닍 Install dependencies"
        uses: reactgular/cache@main
        with:
          mode: "install"

  lint:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - name: "游닌 Checkout code"
        uses: actions/checkout@v4

      - name: "游눻 Restore node_modules cache"
        uses: reactgular/cache@main
        with:
          mode: "restore"

      - name: "游댣 Lint"
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [ install ]
    if: false
    steps:
      - name: "游닌 Checkout code"
        uses: actions/checkout@v4

      - name: "游눻 Restore node_modules cache"
        uses: reactgular/cache@main
        with:
          mode: "restore"

      - name: "游댣 Test"
        run: ${{ env.NX }} affected -t test

  storybooks:
    runs-on: ubuntu-latest
    needs: [ install ]
    if: false
    steps:
      - name: "游닌 Checkout code"
        uses: actions/checkout@v4

      - name: "游눻 Restore node_modules cache"
        uses: reactgular/cache@main
        with:
          mode: "restore"

      - name: "游댣 Build storybooks"
        run: yarn build-storybook

  build:
    runs-on: ubuntu-latest
    #needs: [ lint, test, storybooks ]
    needs: [ lint ]
    steps:
      - name: "游닌 Checkout code"
        uses: actions/checkout@v4

      - name: "游눻 Restore node_modules cache"
        uses: reactgular/cache@main
        with:
          mode: "restore"

      - name: "游댣 Build projects"
        run: yarn build

